on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    check_changes:
        runs-on: ubuntu-latest
        outputs:
          docs_changed: ${{ steps.check_docs.outputs.docs_changed }}
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - id: check_docs
            name: Check if documentation or workflow has changed
            run: |
              if ! git diff --quiet ${{ github.event.before }} ${{ github.sha }} -- docs/ mkdocs.yml .github/workflows/mkdocs.yml || \
                ! git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- . | grep -q '\.py$'; then
                echo "docs_changed=true" >> $GITHUB_OUTPUT
              else
                echo "docs_changed=false" >> $GITHUB_OUTPUT
              fi

    build:
        needs: check_changes
        runs-on: ubuntu-latest
        if: needs.check_changes.outputs.docs_changed == 'true'
        container:
          image: ros:humble

        steps:
            - name: Check Out Repository
              uses: actions/checkout@v4
    
            - name: Install Dependencies
              run: |
                apt-get update
                apt-get install -y python3-pip
                pip3 install --upgrade pip setuptools wheel packaging
                pip3 install -e ./avai_lab[docs]
        
            - name: Build ROS 2 Packages
              shell: bash
              run: |
                source /opt/ros/humble/setup.bash
                cd race_car_ws
                colcon build

            - name: Build MkDocs Site
              shell: bash
              run: |
                source race_car_ws/install/setup.bash
                mkdocs build --verbose --clean

            - name: Upload Site as Artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                name: mkdocs-site-pr-${{ github.event.pull_request.number || 'main' }}
                path: site/

    check_build_or_succeed:
        needs: [check_changes, build]
        runs-on: ubuntu-latest
        steps:
          - name: Check if build succeded or did not need to be triggered
            id: check_success
            run: |
              if [[ "${{ needs.build.result }}" == "success" || "${{ needs.check_changes.outputs.docs_changed }}" == "false" ]]; then
                echo "status=success" >> $GITHUB_OUTPUT
              else
                echo "status=failure" >> $GITHUB_OUTPUT
              fi
      

    deploy:
        if: github.ref == 'refs/heads/main' && needs.check_changes.outputs.docs_changed == 'true'
        runs-on: ubuntu-latest
        needs: [check_changes, build]

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                artifact_name: mkdocs-site-pr-main